### ISSUE TITLE
ERRORS WHEN INSTALLING IN 2022

### ISSUE THREAD

**Issue by EddieSoloProjects** [Unity-Technologies/com.unity.demoteam.digital-human#3]
Library\PackageCache\com.unity.jobs@0.1.1-preview\Unity.Jobs\IJobParallelForDefer.cs(176,85): error CS8377: The type 'U' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'NativeList<T>

**Comment by alexr4** [comment]
Same error appears with Unity 2021.3.X (LTS) but it works on unity 2020.3.X (LTS)

**Comment by EddieSoloProjects** [comment]
> Same error appears with Unity 2021.3.X (LTS) but it works on unity 2020.3.X (LTS)

The Problem is if you also add the Hair Package they just released with it it throws errors on the HDRP project in Unity 2020.3.37f1

**Comment by alexr4** [comment]
I just made a test with the Strand-Based Hair demo package and 2020.3.X. Works perfectly on my side

Here is the package added to the project:
`
"com.unity.demoteam.attributes": "https://github.com/Unity-Technologies/com.unity.demoteam.attributes.git",
"com.unity.demoteam.digital-human": "https://github.com/Unity-Technologies/com.unity.demoteam.digital-human.git",
"com.unity.demoteam.digital-human.sample": "https://github.com/Unity-Technologies/com.unity.demoteam.digital-human.sample.git",
"com.unity.demoteam.hair": "https://github.com/Unity-Technologies/com.unity.demoteam.hair.git",
"com.unity.formats.alembic": "2.2.2",
"com.unity.nuget.newtonsoft-json": "
"com.unity.render-pipelines.high-definition": "10.7.0",
`

**Comment by EddieSoloProjects** [comment]
> 

Yep that's working. At first I thought it didn't because the hair sample scene renders as pure black. But I deleted the camera and made a new one and everything now renders.
